import { documentToReactComponents } from "@contentful/rich-text-react-renderer"
import Head from "next/head"
import Layout from "../../components/Layout"
import { getPost, getPosts, Post } from "../../services/content"

type Props = {
    post: Post
}

export default function PostPage({ post }: Props) {
    return (
        <Layout title={post.fields.title}>
            <div>
                <Head>
                    <title>{post.fields.title} | Coders Blog</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className="w-4/5 m-auto min-h-[21.5rem] p-14">
                    <div className="w-full max-w-4xl m-auto">
                        <img
                            alt="Post thumbnail"
                            src={post.fields.thumbnail.fields.file.url}
                            className="w-full h-[26rem] object-cover rounded-[1.875rem]"
                        />
                    </div>
                    <div className="mt-5 whitespace-pre-wrap">
                        {documentToReactComponents(post.fields.content)}
                    </div>
                </div>
            </div>
        </Layout>
    )
}

export const getStaticProps = async ({ params }) => {
    const post = await getPost(params.id);

    return {
        props: {
            post,
        }
    }
}

export const getStaticPaths = async () => {
    const posts = await getPosts();

    return {
        paths: posts.map((post) => `/post/${post.sys.id}`),
        fallback: false,
    }
}